title = "Site personnel d'Arnaud Brunet"
enableGitInfo = true
uglyURLs = true
languageCode = "fr-FR"
defaultContentLanguage = "fr"
baseURL = '/'

[params]
debug = true
description = "Blog personnel d'Arnaud Brunet"
licence = "CC BY‑NC‑SA 4.0"
publisher = "abrunet"
googleSiteVerification = "Lt8npI-FG_PXE2eiMYUpYhjbWiEsYioooVIP7_UozgQ"

[frontmatter]
lastmod = ["lastmod", ":git", "date"]

[taxonomies]
tag = "tags"
author = "authors"

[markup]
  [markup.highlight]
    noClasses = true
    style = "friendly"
    lineNos = false

[outputs]
home = ["HTML", "RSS", "SITEMAP", "ROBOTS"]
section = ["HTML"]
taxonomy = ["HTML"]
term = ["HTML"]
page = ["HTML"]

[outputFormats.RSS]
mediatype = "application/rss+xml"
baseName = "rss"
isPlainText = true
notAlternative = false

[outputFormats.ROBOTS]
baseName = "robots"
mediaType = "text/plain"
isPlainText = true
