title = "abrunet"
enableGitInfo = true
uglyURLs = true
languageCode = "fr"
defaultContentLanguage = "fr"
baseURL = '/'

[params]
description = "Blog personnel d'Arnaud Brunet"
licence = "CC BY‑NC‑SA 4.0"
publisher = "abrunet"
googleSiteVerification = "Lt8npI-FG_PXE2eiMYUpYhjbWiEsYioooVIP7_UozgQ"
indexnowKey = "d3239a663de041c8a9f3d6f188ee7323"

[frontmatter]
lastmod = ["lastmod", ":git", "date"]

[taxonomies]
tag = "tags"

[markup]
  [markup.highlight]
    noClasses = true
    style = "friendly"
    lineNos = false

[outputs]
home = ["HTML", "RSS", "SITEMAP", "ROBOTS", "IndexNowKey"]
section = ["HTML"]
taxonomy = ["HTML"]
term = ["HTML"]
page = ["HTML"]

[outputFormats.RSS]
mediatype = "application/rss+xml"
baseName = "rss"
isPlainText = true
notAlternative = false

[outputFormats.ROBOTS]
baseName = "robots"
mediaType = "text/plain"
isPlainText = true

[outputFormats.IndexNowKey]
mediaType = "text/plain"
baseName = "indexnow"
isPlainText = true
notAlternative = true
