baseURL = '/'
languageCode = 'fr'
title = 'abrunet.me'
theme = 'abrunet'
enableGitInfo = true
uglyURLs = true

[markup]
  [markup.highlight]
    noClasses = true
    style = "friendly"
    lineNos = false

[frontmatter]
lastmod = ["lastmod", ":git", "date"]

[params]
googleSiteVerification = "Lt8npI-FG_PXE2eiMYUpYhjbWiEsYioooVIP7_UozgQ"
author = "Arnaud Brunet"
description = "Blog personnel d'Arnaud Brunet"

[permalinks]
  posts = "/posts/:contentbasename"
  tags = "/tags/:slug"
  pages = "/:contentbasename"

[outputs]
home = ["HTML", "RSS", "SITEMAP"]
section = []
taxonomy = []
term = ["HTML"]
page = ["HTML"]

[taxonomies]
tag = "tags"
