baseURL = '/'
languageCode = 'fr'
title = 'abrunet.me'
theme = 'abrunet'
enableGitInfo = true

[markup]
  [markup.highlight]
    noClasses = true
    style = "friendly"
    lineNos = false

[frontmatter]
lastmod = ["lastmod", ":git", "date"]

[params]
googleSiteVerification = "Lt8npI-FG_PXE2eiMYUpYhjbWiEsYioooVIP7_UozgQ"