title = 'abrunet.me'
enableGitInfo = true
uglyURLs = true
languageCode = "fr"
defaultContentLanguage = "fr"
baseURL = '/'

[params]
googleSiteVerification = "Lt8npI-FG_PXE2eiMYUpYhjbWiEsYioooVIP7_UozgQ"
author = "Arnaud Brunet"
description = "Blog personnel d'Arnaud Brunet"
licence = "CC BY‑NC‑SA 4.0"

[frontmatter]
lastmod = ["lastmod", ":git", "date"]

[markup]
  [markup.highlight]
    noClasses = true
    style = "friendly"
    lineNos = false

[permalinks]
posts = "/posts/:contentbasename"
tags = "/tags/:slug"
pages = "/:contentbasename"

[outputs]
home = ["HTML", "RSS", "SITEMAP"]
section = []
taxonomy = []
term = ["HTML"]
page = ["HTML"]

[outputFormats.RSS]
mediatype = "application/rss+xml"
baseName = "rss"
isPlainText = true
notAlternative = false

[taxonomies]
tag = "tags"

